name:                ssponge
version:             0.2.0.0
github:              "eunikolsky/ssponge"
license:             BSD3
author:              "Eugene Nikolsky"
maintainer:          "e@egeek.me"
copyright:           "2022 Eugene Nikolsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eunikolsky/ssponge#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  ssponge:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - directory
